global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Diagnostics.CodeAnalysis;
global using System.Text.Json;
global using System.IO;
global using System.Windows;